# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
    build:cli:
        desc: Собрать бинарь bx-pack в директорию dist
        cmds:
            - mkdir -p dist
            - go build -o ./dist/bx-pack ./cmd/bx-pack

    test:
        desc: Запустить все тесты
        cmds:
            - go test -race ./...

    fix:
        desc: Go fix
        cmds:
            - go fix ./...

    check:
        desc: Быстрая локальная проверка
        cmds:
            -   task: vet
            -   task: test

    fmt:
        desc: Отформатировать Go-код
        cmds:
            - go fmt ./...

    vet:
        desc: Запустить go vet
        cmds:
            - go vet ./...

    up:check:
        desc: Проверка на новые версии
        cmd: go list -m -u all

    up:
        desc: Обновить до новых версий
        cmds:
            - go get -u ./...
            - go mod tidy

    ci:
        desc: Полная локальная проверка перед коммитом
        deps:
            - fmt
            - test
            - vet